### ISSUE TITLE
Flexibilizar periodicidade dos dados

### ISSUE THREAD

**Issue by caburu** [ufla-ppoo/Series-de-Dados#6]
O exercício considera que os dados são diários. Mas eles poderiam ser de qualquer periodicidade (horários, semanais, anuais, por partida, etc.).

Para isso seria necessário incluir mais um método que indicasse a periodicidade, além de mudar nomes que estejam vinculados a `dia`.

**Comment by IsraelSantosV** [comment]
Olá, 
Meu grupo, composto por Chrystian, Israel, Luis Wagner e Juliano Godinho, iremos nos dividr em duplas para resolver algumas issues. Para isso, eu e Chrystian gostaríamos de trabalhar nessa issue de flexibilizaçao da periodicidade dos dados.

Obrigado.

**Comment by caburu** [comment]
Olá @IsraelSantosV, bacana que estejam dispostos a colaborar!

Como é um projeto bem simples, não há um procedimento formal para contribuições. Mas, para mantermos as coisas organizadas, seria bom que enviassem a solução da issue na forma de um Pull Request para que eu possa comentar/avaliar a solução.

Qualquer dúvida quanto ao projeto ou à issue em si, estou à disposição.

**Comment by IsraelSantosV** [comment]
Segue o Pull Request da proposta de solução: (https://github.com/ufla-ppoo/Series-de-Dados/pull/8)

**Comment by caburu** [comment]
Resolvido no Pull Request #8
